### ISSUE TITLE
feat[orm]: 能否添加将指定缓存落地的方法

### ISSUE THREAD

**Issue by LucaLq** [zfoo-project/zfoo#118]
> https://github.com/zfoo-project/zfoo/commit/4dffdda93ae3c7c91ccc251c47176b557028a088#commitcomment-143386466

能否保留persist接口，如不想保留，那能否提供个查询缓存的接口。

**Comment by godotg** [comment]
persist接口和updateNow接口功能一样

**Comment by LucaLq** [comment]
> persist接口和updateNow接口功能一样

persist() 和 updateNow()两个方法在场景和落地方式上有不同
场景：
1、updateNow是在已经有cache的情况下使用；
2、persist是在不确定有无缓存的情况下使用，如果有则入库（例如玩家登录时，尝试将另外服上的缓存入库）
落地方式：
1、updateNow是将缓存直接覆盖到DB
2、persist则会判断入库时间和版本，符合条件再入库

我这边有个需求是想知道服务器上是否存在缓存，如果有缓存则落地。目前没找到方法查询缓存，落地也需要自己实现，无法使用updateNow（updateNow会直接将缓存覆盖到DB，没有判断缓存的版本是否最新）

**Comment by godotg** [comment]
了解了，确实有这样的使用场景，我已经回滚了persist()代码
