### ISSUE TITLE
【BUG】：orm关闭时缓存无法落地

### ISSUE THREAD

**Issue by LucaLq** [zfoo-project/zfoo#119]
orm关闭会触发缓存落地，但TaskBus已经在NetContext中关闭了，
https://github.com/zfoo-project/zfoo/blob/4067c9c07d2559d6a4f1e8da92ff488f434f52f0/orm/src/main/java/com/zfoo/orm/cache/EntityCache.java#L279-L284

**Comment by godotg** [comment]
[fix[orm]: cache cannot be persisted when closed application](https://github.com/zfoo-project/zfoo/commit/982e123e877c4273b14da94bfe56c9f44f0b7fec)

在这个提交中提取出了一个方法persistAllBlock()，关闭的时候同步去落地
