### ISSUE TITLE
orm落地优化

### ISSUE THREAD

**Issue by LucaLq** [zfoo-project/zfoo#126]
### 问题
https://github.com/zfoo-project/zfoo/blob/a721f6d5ff1ee110595d173894a42c3d1baa3f98/orm/src/main/java/com/zfoo/orm/cache/EntityCache.java#L343

getModifiedCount和batchList.size不一致的原因有两个

1. 数据库中没有查到目标数据
2. 要更新的数据和DB中的数据一致

getModifiedCount和batchList.size不一致后会再次执行persistAllAndCompare方法，但persistAllAndCompare方法并不能解决上面两个问题，反而增加了DB的压力。

### 解决方案
1. 数据库中没有查到目标数据 => 业务上通过loadOrCreate获取缓存，保证数据库中一定有数据
2. 更新数据和DB中的数据一致 => 这种无需处理，认为更新成功即可
3. 判断逻辑改成`if (result.getMatchedCount() == batchList.size())`
    > 匹配数量不一致的原因只能是`要更新的数据和DB中的数据版本不一致`，这个时候可以通过persistAllAndCompare方法落地来解决

**Comment by LucaLq** [comment]
@godotg 作者帮忙看看这样修改是否合理

**Comment by godotg** [comment]
仔细想了一下，使用getMatchedCount()确实更加合理一点，可以极大减少数据库的压力，欢迎提pr
