### ISSUE TITLE
网关服不重启，逻辑服重启后，怎么还原session连接

### ISSUE THREAD

**Issue by dillonnet** [zfoo-project/zfoo#19]
网关服不重启，逻辑服重启后，怎么还原session连接
用户登录后，每个socket连接存有uid对应哪个玩家， 逻辑服重启后会丢失uid, 怎么关联？

**Comment by godotg** [comment]
逻辑服重启后自动会和网关建立连接

**Comment by dillonnet** [comment]
重新建议连接后会丢失uid

**Comment by godotg** [comment]
描述你遇到的问题，简洁有效的说明
如何重现问题，描述遇到的问题的发生步骤
