### ISSUE TITLE
服务启动后，有些方法标志为EventReceiver可以注册，有些注册不了

### ISSUE THREAD

**Issue by dillonnet** [zfoo-project/zfoo#20]
https://github.com/zfoo-project/zfoo/blob/f5c8f3b9ea57b58a15e3b5125b2fea39c94ffb10/event/src/main/java/com/zfoo/event/schema/EventRegisterProcessor.java#L45

在网上也有人提出这个问题， method的Annotation一直都为空， method.isAnnotationPresent(annotation)返回false

https://stackoverflow.com/questions/53794925/isannotationpresent-returning-false-always

**Comment by godotg** [comment]
没有说明，这个class类没有被EventReceiver这个注解标注的方法

**Comment by godotg** [comment]
描述你遇到的问题，简洁有效的说明
如何重现问题，描述遇到的问题的发生步骤

**Comment by dillonnet** [comment]
我发现问题了，Java反射类方法isAnnotationPresent(Class)无法判断代理类方法是否包含注解，如果有方法标记了@Transactional，zfoo就无法注册这个类

**Comment by dillonnet** [comment]
https://blog.csdn.net/q283614346/article/details/102903500
