### ISSUE TITLE
Orm模块可以支持在一个JVM进程里访问两个Mongodb的Database么？

### ISSUE THREAD

**Issue by endison1986** [zfoo-project/zfoo#34]
Orm模块可以支持在一个JVM进程里访问两个Mongodb的Database么？

**Comment by godotg** [comment]
可以的，等后面支持下

**Comment by godotg** [comment]
如果有兴趣改，欢迎提交pr

**Comment by godotg** [comment]
IOrmManager 增加了一个 mongoClient 的api，通过这个接口可以获得到其它的数据库，然后通过数据库获得集合，就可以操作其它数据库了
