### ISSUE TITLE
全服广播, 单服广播

### ISSUE THREAD

**Issue by bobwong89757** [zfoo-project/zfoo#61]
请问大佬有没有全服(所有网关的所有合法用户)广播的例子?

**Comment by godotg** [comment]
var notice = GroupChatMessageNotice.valueOf(entity.toChatMessage());
        // 广播给全服玩家
        NetContext.getSessionManager().forEachServerSession(it -> NetContext.getRouter().send(it, notice));

**Comment by bobwong89757** [comment]
感谢
