### ISSUE TITLE
作者可以再提供两个方法,编解码根据byte[]  吗？

### ISSUE THREAD

**Issue by 110jiangnan** [zfoo-project/zfoo#65]
你的案例中是序列化和反序列化是根据io.netty.buffer，返回的也是buffer。想要得到byte[],就需要转化，能否像jprotobuf一样，根据byte[]来序列化。

![image](https://github.com/zfoo-project/zfoo/assets/87222759/90b6c9ad-76a2-4f32-a2d0-926546244ca5)

**Comment by godotg** [comment]
byte[]转ByteBuf使用netty自带的Unpooled.wrappedBuffer(byte[])

ByteBuf转byte[]使用zfoo封装的ByteBufUtils.readAllBytes(byte[])

**Comment by godotg** [comment]
> 你的案例中是序列化和反序列化是根据io.netty.buffer，返回的也是buffer。想要得到byte[],就需要转化，能否像jprotobuf一样，根据byte[]来序列化。
> 
> ![image](https://user-images.githubusercontent.com/87222759/261755441-90b6c9ad-76a2-4f32-a2d0-926546244ca5.png)

ByteBuf 支持zero copy，尽量不要转成byte[]数组

**Comment by 110jiangnan** [comment]
@godotg 因为我想把zfoo序列化单独拿出来用于一些项目的扩展，要求返回byte[]。这样就不需要引入netty包了，而且bytebuf和byte[]互转又浪费了一个对象内存

**Comment by godotg** [comment]
@110jiangnan 不想浪费对象内存可以使用池化的PooledHeapByteBuf
