### ISSUE TITLE
为什么把老版本删了，这样项目很不稳定，线上项目怎么放心

### ISSUE THREAD

**Issue by 3ho** [zfoo-project/zfoo#85]
别人的线上项目怎么维护，3.0版本的完全找不到了，让我很头痛，第一次遇到把老版本删除的，我不管你出于什么理由，这件事做的很不好，无可往回的错。
框架最重要的就是可维护性

**Comment by godotg** [comment]
之前的3.0版本没有发release，我已经把他切到另一个[3.0分支](https://github.com/zfoo-project/zfoo/tree/zfoo-java-11-17)

第一个release是3.1.4版本并且上传到了maven中央仓库，新版本是集成了Graalvm支持，其它的用法没有太大改变，主要就是不强制继承IPacket接口。

**Comment by 3ho** [comment]
嗯，谢谢

**Comment by godotg** [comment]
- 主干main是当前是面向java 21和GraalVM的开发版本，稳定版本请使用 [zfoo-java-11-17](https://github.com/zfoo-project/zfoo/tree/zfoo-java-11-17)
- 升级流程
    - 重新导入找不到的类
    - 不需要再继承IPacket
    - SafeRunnable删除了，请使用ThreadUtils.safeRunnable()
    - 重命名接口和注解，Storage -> IStorage，@Resource -> @Storage，@ResInjection -> @StorageAutowired
    - 重命名接口和注解，@EntityCachesInjection -> @EntityCacheAutowired，@EntityCaches -> @EntityCache

**Comment by godotg** [comment]
推荐使用 3.2.0的版本，已经是稳定的release版本了
