### ISSUE TITLE
考虑出一个其他语言与java进行TCP通讯的示例么？

### ISSUE THREAD

**Issue by linfu98546** [zfoo-project/zfoo#98]
目前尝试用C#与用该框架搭建的Java项目进行TCP通讯，不知道如何进行对接。

**Comment by godotg** [comment]
[zfoo sdk of csharp and lua for unity and godot](https://github.com/zfoo-project/zfoo-sdk-csharp-lua-unity-godot)

**Comment by godotg** [comment]
[C#的网络层代码copy出去就能用](https://github.com/zfoo-project/zfoo-sdk-csharp-lua-unity-godot/tree/main/Assets/Net)

**Comment by linfu98546** [comment]
好的，谢谢
